# Generated by Django 5.2.13 on 2026-05-10 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_aimodelsettings_remove_prediction_top_predictions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(choices=[('efficientnet', 'EfficientNet'), ('mobilenet', 'MobileNet'), ('resnet', 'ResNet')], max_length=50)),
                ('prediction_label', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('prediction_time', models.FloatField(help_text='Time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
