# Generated by Django 5.2.13 on 2026-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_predictionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelsettings',
            name='active_model',
            field=models.CharField(choices=[('efficientnet', 'EfficientNet'), ('mobilenet', 'MobileNet'), ('resnet', 'ResNet')], default='efficientnet', max_length=100),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='model_used',
            field=models.CharField(default='efficientnet', max_length=100),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='prediction_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='prediction_time',
            field=models.FloatField(),
        ),
    ]
